[package]
name = "benchmark-data-update"
version = "0.1.0"
authors = ["Serge Farny <serge.farny@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
mango-feeds-connector = { workspace = true }
mango-feeds-lib = { path = "../../lib/mango-feeds-lib" }
services-mango-lib = { path = "../../lib/services-mango-lib" }

solana-client = { workspace = true }
solana-logger = { workspace = true }
solana-sdk = { workspace = true }

anchor-lang = { workspace = true }
anchor-client = { workspace = true }

fixed = { workspace = true, features = ["serde", "borsh"] }

mango-v4 = { path = "../../programs/mango-v4", features = ["client"] }
mango-v4-client = { path = "../../lib/client" }

serum_dex = { workspace = true }

bs58 = "0.3.1"
log = "0.4"
anyhow = "1.0"
toml = "0.5"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
futures = "0.3.17"
futures-core = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
ws = "^0.9.2"
async-channel = "1.6"
async-trait = "0.1"
bytemuck = "^1.7.2"
itertools = "0.10.3"
jemallocator = "0.3.2"
chrono = "0.4.23"
base64 = "0.21"

tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.17"

native-tls = "0.2"
rustls = "0.20.8"
tracing = { version = "0.1", features = ["log"] }

hdrhistogram = "7.5.4"
