FROM rust:1.60 as builder

RUN apt-get -y update
RUN apt-get -y dist-upgrade
RUN apt-get -y install build-essential gcc libssl-dev
RUN apt-get -y install clang
RUN apt-get -y install cmake

WORKDIR /usr/src/mango-v4
COPY . .
COPY ./cargo /usr/local/cargo

RUN cargo build --release --package keeper
COPY target/release/keeper /usr/local/bin

FROM debian:buster-slim
COPY --from=builder /usr/local/bin /usr/local/bin

CMD ["keeper"]