bind_ws_addr = "0.0.0.0:8080"
rpc_http_url = "http://mango.rpcpool.com/<TOKEN>"
mango_group = "78b8f4cGCwmZ9ysPFMWLaLTkkaYnUjwMJYStWe5RTSSX"

[metrics]
output_stdout = true
output_http = false

# [postgres]
# connection_string = "$PG_CONNECTION_STRING"
# allow_invalid_certs = true

# # [postgres.tls]
# # ca_cert_path = "$PG_CA_CERT"
# # client_key_path = "$PG_CLIENT_KEY"

[source]
dedup_queue_size = 50000
rpc_ws_url = "wss://mango.rpcpool.com/<TOKEN>"

[[source.grpc_sources]]
name = "accountsdb-client"
connection_string = "http://tyo64.rpcpool.com/"
retry_connection_sleep_secs = 30

[source.snapshot]
rpc_http_url = "http://mango.rpcpool.com/<TOKEN>"
program_id = "4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg"

[computing_configuration]
recompute_interval_ms = 100

[logging_configuration]
log_health_to_stdout = true
#log_health_for_accounts = ["xxx"]
