rpc_http_url = "$RPC_HTTP_URL"
mango_group = "78b8f4cGCwmZ9ysPFMWLaLTkkaYnUjwMJYStWe5RTSSX"

[postgres]
connection_string = "$PG_CONNECTION_STRING"
max_retry_count = 2
allow_invalid_certs = true

[postgres.tls]
ca_cert_path = "$PG_CA_CERT"
client_key_path = "$PG_CLIENT_KEY"

[source]
rpc_ws_url = "$RPC_WS_URL"

[source.snapshot]
rpc_http_url = "$RPC_HTTP_URL"
program_id = "4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg"

[computing_configuration]
recompute_interval_ms = 100

[logging_configuration]
log_health_to_stdout = false
