# Address of Solana JSON RPC pubsub websocket
rpc_ws_url = "ws://api.mainnet-beta.solana.com"

# Address of Solana JSON RPC endpoint
#
# The endpoint must support getProgramAccounts requests: the
# example address here does not.
rpc_http_url = "https://api.mainnet-beta.solana.com"

# Configuration of Mango related addresses, so the program knows
# what to look at.
mango_program_id = "mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68"
pyth_program_id = "gSbePebfvPy7tRqimPoVecS2UsBvYv46ynrzWocc92s"
mango_group_id = "98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue"
mango_signer_id = "9BVcYqEQxyccuwznvxXqDkSJFavvTyheiTYk231T1A8S"
serum_program_id = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"

# Interval between requesting getProgramAccounts data snapshots
snapshot_interval_secs = 240

# Number of parallel getMultipleAccounts requests to send during snapshotting.
parallel_rpc_requests = 10
# Number of accounts that can be retrieved in a getMultipleAccounts call.
# Typically 100 for normal RPC nodes.
get_multiple_accounts_count = 100

# FUTURE: separate into a separate conf file? we are mixing feed + mango client conf in one place here
# mango client specific
payer = "/root/.config/solana/id.json"
mango_account_name = "Taker"
