app = "switchboard-crank"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "../ts/client/scripts/Dockerfile.scripts"

[experimental]
  cmd = ["yarn", "tsx", "ts/client/scripts/sb-on-demand-crank.ts"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
