name: Deploy Docker Image to Heroku

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'Heroku App Name'
        required: true
        type: string
      imageName:
        description: 'Docker Image Name'
        required: true
        type: string
      imageTag:
        description: 'Docker Image Tag'
        required: true
        type: string
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          IMAGE_NAME: ${{ inputs.imageName }}
          APP_NAME: ${{ inputs.appName }}
          IMAGE_TAG: ${{ inputs.imageTag }}
        run: heroku container:push "$IMAGE_NAME" -a "$APP_NAME" --recursive --arg BASE_TAG="$IMAGE_TAG"

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          IMAGE_NAME: ${{ inputs.imageName }}
          APP_NAME: ${{ inputs.appName }}
        run: heroku container:release "$IMAGE_NAME" -a "$APP_NAME"
