name: PR Labels
on:
  pull_request:
    types: [opened, synchronize]
    branches: [dev]

jobs:
  label:
    name: Add PR labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Run label config
        uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
