name: Verifiable Build
on:
  push:
    tags:
      - "program-v*"

env:
  APP_NAME: mango_v4

jobs:
  build:
    name: Build Verifiable Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Verifiable Build
        run: |
          cargo run -p anchor-cli -- build --verifiable --solana-version 1.14.13 -- --features enable-gpl

      - name: Generate Checksum
        run: |
          echo "CHECKSUM=$(sha256sum ./target/verifiable/${{ env.APP_NAME }}.so)" >> $GITHUB_ENV

      - name: Generate SBOM
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'cyclonedx'
          output: '${{ env.APP_NAME }}-${{ github.ref_name }}-sbom.json'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            sha256 checksum: ${{ env.CHECKSUM }}
            github commit: ${{ github.sha }}

      - name: Upload Build Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # default working directory only applies to 'run' steps, hardcoded workspace path for now
          asset_path: ./dex/target/verifiable/${{ env.APP_NAME }}.so
          asset_name: ${{ env.APP_NAME }}.so
          asset_content_type: application/x-sharedlib

      - name: Upload SBOM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dex/${{ env.APP_NAME }}-${{ github.ref_name }}-sbom.json
          asset_name: ${{ env.APP_NAME }}-${{ github.ref_name }}-sbom.json
          asset_content_type: application/json
